sudo: true

dist: xenial

language: python

python:
- 2.7
- 3.4
- 3.5
- 3.6
- 3.7
- 3.8-dev
- pypy3.5

install:
- pip install --upgrade coveralls flake8 pyflakes tox

script:
- tox

after_success:
- coveralls
